name: Pre-deploy Script

on:
  push:
    branches:
      - main  # or your deploy branch

jobs:
  predeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Python script
        run: |
	      cd playlist
		  python generate_html.py
          git add .
          git commit -m "Pre-deploy file edits"
          git push

